name: test

on:
    push:
        branches: []

jobs:
    test-on-macos-latest:
        runs-on: macos-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    node-version: 18
                    cache: npm
            -   name: Install
                run: npm run chore
            -   name: Build
                run: npm run build
    test-on-ubuntu-latest:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    node-version: 18
                    cache: npm
            -   name: Install
                run: npm run chore
            -   name: Build
                run: npm run build
    test-on-windows-latest:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    node-version: 18
                    cache: npm
            -   name: Install
                run: npm run chore
            -   name: Build
                run: npm run build
